version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: laravel_app_container
    volumes:
      - ../:/var/www/html   # Mount local code for dev
    ports:
      - "9000:9000"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    container_name: laravel_nginx_container
    ports:
      - "8009:80"
    depends_on:
      - app
    volumes:
      - ../:/var/www/html

  db:
    image: mysql:8.0
    container_name: laravel_mysql_container
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata: